check_values: {x_dom_charge_mean: 0.19201043042397908, x_dom_charge_std: 0.795967265198242,
  x_parameters_mean: 1590.5864340485903, x_parameters_std: 1081.0109716317763}
class_string: egenerator.data.trafo.DataTransformer
dependent_sub_components: []
event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
event_generator_origin: ssh://git@github.com/icecube/event-generator.git
event_generator_uncommitted_changes: true
event_generator_version: 1.0.1-dev
mutable_settings: {}
mutable_sub_components: []
settings:
  data_iterator_settings:
    batch_capacity: 2
    batch_size: 32
    file_capacity: 1
    input_data: [/data/i3home/sgray/egen/repositories/event-generator/create_labels/cascades/datasets/21220/21220_DOMPulseData_0000*.hdf5,
      /data/i3home/sgray/egen/repositories/event-generator/create_labels/cascades/datasets/21220/21220_DOMPulseData_00001*.hdf5]
    num_add_files: 1
    num_jobs: 20
    num_repetitions: 1
    num_splits: null
    pick_random_files_forever: true
  float_precision: float64
  norm_constant: 1e-06
  num_batches: 5000
sub_component_configurations:
  data_handler:
    check_values: {}
    class_string: egenerator.data.handler.modular.ModuleDataHandler
    dependent_sub_components: [data_module, label_module, weight_module, misc_module,
      filter_module]
    event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
    event_generator_origin: ssh://git@github.com/icecube/event-generator.git
    event_generator_uncommitted_changes: true
    event_generator_version: 1.0.1-dev
    mutable_settings:
      config:
        data_handler: modular.ModuleDataHandler
        data_module: pulse_data.PulseDataModule
        data_settings: {add_charge_quantiles: false, discard_pulses_from_excluded_doms: false,
          dom_exclusions_key: BrightDOMs, float_precision: float32, pulse_key: masked_pulses,
          time_exclusions_key: time_exclusion}
        filter_module: general_filter.GeneralFilterModule
        filter_settings:
          constraints: []
        label_module: snowstorm_cascades.SnowstormCascadeGeneratorLabelModule
        label_settings:
          float_precision: float32
          label_key: LabelsDeepLearning
          num_snowstorm_params: 0
          shift_cascade_vertex: true
          snowstorm_key: SnowstormParameters
          trafo_log: [false, false, false, false, false, true, false]
        misc_module: dummy.DummyMiscModule
        misc_settings: {}
        weight_module: dummy.DummyWeightModule
        weight_settings: {}
    mutable_sub_components: [weight_module, misc_module, filter_module, label_module]
    settings: {}
    sub_component_configurations:
      data_module:
        check_values: {}
        class_string: egenerator.data.modules.data.pulse_data.PulseDataModule
        dependent_sub_components: []
        event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
        event_generator_origin: ssh://git@github.com/icecube/event-generator.git
        event_generator_uncommitted_changes: true
        event_generator_version: 1.0.1-dev
        mutable_settings: {discard_pulses_from_excluded_doms: false, dom_exclusions_key: BrightDOMs,
          pulse_key: masked_pulses, time_exclusions_key: time_exclusion}
        mutable_sub_components: []
        settings: {add_charge_quantiles: false, config_data: null, float_precision: float32}
        sub_component_configurations: {}
      filter_module:
        check_values: {}
        class_string: egenerator.data.modules.filters.general_filter.GeneralFilterModule
        dependent_sub_components: []
        event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
        event_generator_origin: ssh://git@github.com/icecube/event-generator.git
        event_generator_uncommitted_changes: true
        event_generator_version: 1.0.1-dev
        mutable_settings: {}
        mutable_sub_components: []
        settings:
          config_data: null
          constraints: []
        sub_component_configurations: {}
      label_module:
        check_values: {}
        class_string: egenerator.data.modules.labels.snowstorm_cascades.SnowstormCascadeGeneratorLabelModule
        dependent_sub_components: []
        event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
        event_generator_origin: ssh://git@github.com/icecube/event-generator.git
        event_generator_uncommitted_changes: true
        event_generator_version: 1.0.1-dev
        mutable_settings: {}
        mutable_sub_components: []
        settings:
          additional_labels: []
          config_data: null
          float_precision: float32
          label_key: LabelsDeepLearning
          num_snowstorm_params: 0
          shift_cascade_vertex: true
          snowstorm_key: SnowstormParameters
          trafo_log: [false, false, false, false, false, true, false]
        sub_component_configurations: {}
      misc_module:
        check_values: {}
        class_string: egenerator.data.modules.misc.dummy.DummyMiscModule
        dependent_sub_components: []
        event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
        event_generator_origin: ssh://git@github.com/icecube/event-generator.git
        event_generator_uncommitted_changes: true
        event_generator_version: 1.0.1-dev
        mutable_settings: {}
        mutable_sub_components: []
        settings: {config_data: null}
        sub_component_configurations: {}
      weight_module:
        check_values: {}
        class_string: egenerator.data.modules.weights.dummy.DummyWeightModule
        dependent_sub_components: []
        event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
        event_generator_origin: ssh://git@github.com/icecube/event-generator.git
        event_generator_uncommitted_changes: true
        event_generator_version: 1.0.1-dev
        mutable_settings: {}
        mutable_sub_components: []
        settings: {config_data: null}
        sub_component_configurations: {}
