---
##############
# Config for ICU events
#
# Detailed information on the parameters are given in the SetupManager
# class located in egenerator.settings.setup_manager.py.
##############

# Provide a unique name for the model
unique_name: 'astro_tau'

#Pickle file
detector_pickle: &detector_pickle '/storage/work/jcw5951/event-generator/gcd_preprocessing/geometry_pickles/IceCube.pickle'
#------------------
# Training settings
#------------------
training_settings: {
    'optimizer_name': 'Adam',
    'optimizer_settings': {
        # 'amsgrad': True,
        'learning_rate': {
            'full_class_string': 'egenerator.utils.learning_rate.MultiLearningRateScheduler',
            'settings':{
                'boundaries': [10000, 500000],
                'scheduler_settings': [
                    {
                    'full_class_string': 'tensorflow.keras.optimizers.schedules.PolynomialDecay',
                    'settings': {
                        'initial_learning_rate': 0.01,
                        'end_learning_rate': 0.001,
                        'decay_steps': 10000,
                        },
                    },
                    {
                    'full_class_string': 'tensorflow.keras.optimizers.schedules.PolynomialDecay',
                    'settings': {
                        'initial_learning_rate': 0.001,
                        'end_learning_rate': 0.001,
                        'decay_steps': 490000,
                        },
                    },
                    {
                    'full_class_string': 'tensorflow.keras.optimizers.schedules.PolynomialDecay',
                    'settings': {
                        'initial_learning_rate': 0.001,
                        'end_learning_rate': 0.000001,
                        'decay_steps': 500000,
                        'power': 2,
                        },
                    },
                ]
            },
        },
    },
    'l1_regularization': 0.,
    'l2_regularization': 0.,
    'clip_gradients_value': ,
    'remove_nan_gradients': False,

    'validation_frequency': 500,
    'evaluation_frequency': 500,
    'save_frequency': 500,

    # Number of training iterations to train the model for
    'num_training_iterations': 20000, #200000

    # Additional keywords to the loss module used for #training
    'additional_loss_module_kwargs': {
        'normalize_by_total_charge': False,
    },
}

#----------------.-------
# Reconstruction settings
#------------------------
reconstruction_settings: {
    'reco_output_file': '/storage/work/jcw5951/event-generator/data/reco/reco_{unique_name}.hdf5',

    # Define which modules to run
    'calculate_covariance_matrix': False,
    'calculate_goodness_of_fit': False,
    'estimate_angular_uncertainty': False,
    'run_mcmc': False,
    'make_1d_llh_scans': False,

    # define which tensor to use as parameter_tensor (default: x_parameters)
    'parameter_tensor_name': 'x_parameters',
    # define seed (to seed from MC truth choose: 'x_parameters')
    'seed': 'x_parameters',
    # these are only relevant for the SeedLoaderMiscModule. This specifies
    # from which column names in the data table the parameters will be loaded
    'seed_parameter_names': ['x', 'y', 'z', 'zenith', 'azimuth', 'energy', 'time', 'energy2', 'distance'],
    'seed_missing_value': None,
    'seed_missing_value_dict': {
    },
    'seed_float_precision': 'float32',

    # choose the otpimizer iterface:
    #   'scipy' or 'tfp' (tensorflow_probability)
    'reco_optimizer_interface': 'scipy',

    'scipy_optimizer_settings': {
        'method': 'L-BFGS-B',
        #'method': 'BFGS',
        'bounds': [[-700, 800], [-700, 750], [-850, 600], [0, 3.14], [0, 6.28], [100, 50000000], [8000, 12000], [0, 50000000], [0, 200]],
        #'bounds': [[-700, 800], [-700, 750], [-850, 600], [0, 3.14], [0, 6.28], [100, 50000000], [8000, 12000], [0, 1], [0, 0.1]],
        'options': {
            # 'ftol': !!float 1e-7,
        }
    },

    'tf_optimizer_settings': {
        'method': 'bfgs_minimize',
        'x_tolerance': 0.001,
    },

    'spherical_optimizer_settings': {
        'limits': [[-700, 800], [-700, 750], [-850, 600], [0, 3.14], [0, 6.28], [100, 50000000], [8000, 12000], [0, 50000000], [0, 200]],
        'seed_box': [[-100, 100], [-100, 100], [-100, 70], [-1, 1], [0, 6.28], [2, 7], [-4000, -1000], [-1, 7], [-2, 1.5]],
        'batch_size': 12,
        'detector_pickle': *detector_pickle,
        'noise': True,
    },

    # Perform minimization in transformed and normalized parameter space
    # if True. This is usually desired as it may facilitate minimization.
    'minimize_in_trafo_space': True,

    # Specify which parameters to fit.
    # If True, the parameter is minimized doing reconstruction, otherwise it
    # is held constant.
    # Set default value which will apply to all parameters, except if stated
    # otherwise in the 'minimize_parameter_dict'
    'minimize_parameter_default_value': True,
    # Settings defined here overwrite the default value
    # Entries must have the form: {parameter_name: value}
    'minimize_parameter_dict': {
        #'double_cascade_energy2': 0.,
        #'double_cascade_distance': 0.
    },
}

#-----------------------
# Model Manager settings
#-----------------------

# Settings for model manager class
model_manager_settings: {

    # The loss module class to use
    'model_manager_class': 'egenerator.manager.source.SourceManager',

    # restore model if True, otherwise start from scratch
    'restore_model' : True,

    # These settings are used to configure the model manager and may not change
    config: {

        # Path to where the manager will be saved to and loaded from
        'manager_dir': '/storage/work/jcw5951/event-generator/models/{unique_name}/manager',

        # optical module/detector geometry to use
        'optical_module_key': *detector_pickle,

        # Define which model parameters to use for the I3Particle
        # [x, y, z, zenith, azimuth, energy, time]
        'I3ParticleMapping': {
            'x': 'TauPositionX',
            'y': 'TauPositionY',
            'z': 'TauPositionZ',
            'zenith': 'TauZenith',
            'azimuth': 'TauAzimuth',
            'energy': 'Cascade1Energy',
            'time': 'TauTime',
            #'energy2': 'Cascade2Energy',
            #'distance': 'TauLength',
        },
    },
}

#-----------------------
# Data Iterator settings
#-----------------------

# These settings describe the data iterators
data_iterator_settings: {

    # The training data iterator
    'training': {
        'batch_size': 16,
        'num_splits': ,
        'file_capacity': 10,
        'batch_capacity': 500,
        'dataset_capacity': 500,
        'num_jobs': 10,
        'num_add_files': 20,
        'num_repetitions': 3,
        'pick_random_files_forever': True,
        'input_data': [
            '/storage/group/dfc13/default/AstroTau/train/*zst.hdf5',
            '/storage/group/dfc13/default/AstroTau/train/*_single.hdf5',
        ],
    },

    # The trafo data iterator
    'trafo': {
        'batch_size': 16,
        'num_splits': ,
        'file_capacity': 1,
        'batch_capacity': 2,
        'num_jobs': 10,
        'num_add_files': 1,
        'num_repetitions': 1,
        'pick_random_files_forever': False,
        'input_data': [
            '/storage/group/dfc13/default/AstroTau/train/*.hdf5',
        ],
    },

    # The validation data iterator
    'validation': {
        'batch_size': 16,
        'num_splits': ,
        'file_capacity': 5,
        'batch_capacity': 10,
        'dataset_capacity': 10,
        'num_jobs': 2,
        'num_add_files': 5,
        'num_repetitions': 1,
        'pick_random_files_forever': True,
        'input_data': [
            '/storage/group/dfc13/default/AstroTau/valid/*zst.hdf5',
            '/storage/group/dfc13/default/AstroTau/valid/*_single.hdf5',
        ],
    },

    # The test data iterator
    'test': {
        'batch_size': 1,
        'num_splits': ,
        'file_capacity': 1,
        'batch_capacity': 3,
        'num_jobs': 1,
        'num_add_files': 0,
        'num_repetitions': 1,
        'sample_randomly': False,
        'pick_random_files_forever': False,
        'input_data': [
            '/storage/group/dfc13/default/AstroTau/valid/Level2_IC86.2020_NuTau.021989.0000*0.i3.zst.hdf5',
            '/storage/group/dfc13/default/AstroTau/valid/Level2_IC86.2020_NuTau.021989.0000*0.i3.zst_single.hdf5',
        ],
    },
}

#--------------------
#Loss module settings
#---------------------

# Settings for the loss module class
loss_module_settings: [
    {
        # The loss module class to use
        'loss_module': 'egenerator.loss.default.DefaultLossModule',

        config: {
            # the float precision to use
            'float_precision': 'float32',
            # Add normalization terms to llh if True
            'add_normalization_term': True,
            # choose the loss function to use
            'loss_function_name': 'unbinned_pulse_time_llh',
            # optical module to use
            'optical_module_key': *detector_pickle,
            # convert charges to integers
            'int_charges': True,
        },
    },
    {
        # The loss module class to use
        'loss_module': 'egenerator.loss.default.DefaultLossModule',

        config: {
            # the float precision to use
            'float_precision': 'float32',
            # Add normalization terms to llh if True
            'add_normalization_term': True,
            # choose the loss function to use
            'loss_function_name': 'negative_binomial_charge_pdf', #negative_poisson_charge_pdf
            # optical module to use
            'optical_module_key': *detector_pickle,
            # convert charges to integers
            'int_charges': True,
        },
    },
]

#---------------------------
# Evaluation module settings
#---------------------------

# Settings for the evaluation module class
evaluation_module_settings: {

    # The loss module class to use
    'evaluation_module':,
    config: {
    },
}

#-----------------------------
# Data Transformation settings
#-----------------------------
data_trafo_settings: {
    'float_precision': 'float64',
    'norm_constant': !!float 1e-6,
    'num_batches': 3000,
    'model_dir': '/storage/work/jcw5951/event-generator/trafo_models/pulses_astro_tau',
}

#----------------------
# Data Handler settings
#----------------------

# Settings for the data handler class
data_handler_settings: {

    # The data handler class to use
    'data_handler': 'modular.ModuleDataHandler',

    # -------------------
    # DataModule Settings
    # -------------------
    # which data module to use
    'data_module': 'pulse_data.PulseDataModule',

    # settings for the data module
    'data_settings':{
        'pulse_key': 'InIcePulses',
        'dom_exclusions_key':,
        'time_exclusions_key':,
        'float_precision': 'float32',
        'add_charge_quantiles': False,
        'discard_pulses_from_excluded_doms': False,
        'optical_module_key': *detector_pickle
    },

    # --------------------
    # LabelModule Settings
    # --------------------
    # which label module to use
    'label_module': 'astro_tau.AstroTauGeneratorLabelModule',

    # settings for the label module
    'label_settings':{
        'shift_cascade_vertex': False,
        # logarithm on labels:
        # (x, y, z, zenith, azimuth, E1, time, E2, distance)
        'trafo_log': [False, False, False, False, False, True, False, True, False],
        'label_key': 'LabelsDeepLearning',
        'additional_labels': ['Cascade2Energy', 'TauLength'],
        'float_precision': 'float32',
    },

    # ---------------------
    # WeightModule Settings
    # ---------------------
    # which weight module to use
    'weight_module': 'dummy.DummyWeightModule',

    # settings for the weight module
    'weight_settings':{},

    # -------------------
    # MiscModule Settings
    # -------------------
    # which misc module to use
    'misc_module': 'dummy.DummyMiscModule',

    # settings for the misc module
    'misc_settings':{},

    # -------------------
    # FilterModule Settings
    # -------------------
    # which filter module to use
    'filter_module': 'dummy.DummyFilterModule',

    # settings for the filter module
    'filter_settings':{
        'constraints': [
            #['LabelsDeepLearning', 'TauLength', '==', 0.],
            ['LabelsDeepLearning', 'TauLength', '<', 200.],
        ],
    },
}


#---------------
# Model settings
#---------------

# Settings for the neural network model class
model_settings: {

    # The source class to use
    'model_class': 'egenerator.model.multi_source.independent.IndependentMultiSource',

    # configuration settings for DefaultMultiCascadeModel object
    config: {
        'optical_module_key': *detector_pickle,
        'sources': {
            'noise': 'noise',
            'double_cascade': 'double_cascade',
        },
    },

    # Base sources used by the multi-source class
    multi_source_bases: {

        noise: {
            # The noise source model class to use
            'model_class': 'egenerator.model.source.noise.default.DefaultNoiseModel',
            config: {
            'optical_module_key': *detector_pickle,
            },
        },

        double_cascade: {
            # The event source model class to use
            'model_class': 'egenerator.model.multi_source.astro_tau.double_cascade.DoubleCascadeModel',
            
            # configuration settings for DefaultMultiCascadeModel object
            config: {
                'optical_module_key': *detector_pickle,
                'sources': {
                    'cascade': 'cascade',
                },
            },
            
            # Base sources used by the multi-source class
            multi_source_bases: {

                cascade: {
                    'model_class': 'egenerator.model.source.cascade.default.DefaultCascadeModel',
                    
                    # define data trafo settings for the base source
                    data_trafo_settings: {
                        'float_precision': 'float64',
                        'norm_constant': !!float 1e-6,
                        'num_batches': 3000,
                        'model_dir': '/storage/work/jcw5951/event-generator/trafo_models/pulses_astro_tau_cscd',
                    },

                    config: {
                        'keep_prob':,
                        'add_opening_angle': True,
                        'add_dom_coordinates': False,
                        'num_local_vars': 0,
                        'scale_charge': True,
                        'scale_charge_by_relative_dom_efficiency': True,
                        'scale_charge_by_global_dom_efficiency': False,
                        'prevent_mixture_component_swapping': False,
                        'estimate_charge_distribution': 'negative_binomial',
                        'optical_module_key': *detector_pickle,
                        'num_latent_models': 10,

                        # This is a list of labels in addition to
                        # 
                        'additional_label_names' : [
                        ],

                        # First convolutions
                        'filter_size_list' : [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]],
                        'num_filters_list' : [25, 350, 350, 350, 42],
                        'method_list' : ['locally_connected',
                                         'convolution', 'convolution', 'convolution',
                                         'convolution',
                                         ],
                        'use_dropout_list' : False,
                        'activation_list' : ['elu', 'elu', 'elu', 'elu',''],
                        'use_batch_norm_list' : False,
                        'use_residual_list' : True,
                    },
                },
            },
        },  
    },
}

#----------------------
