---
##############
# Config for single cascade events
#
# Detailed information on the parameters are given in the SetupManager
# class located in egenerator.settings.setup_manager.py.
##############

# Provide a unique name for the model
unique_name: 'cascade_7param_MCPE'


#------------------
# Training settings
#------------------
training_settings: {
    'optimizer_name': 'Adam',
    'optimizer_settings': {
        # 'amsgrad': True,
        'learning_rate': {
            'full_class_string': 'egenerator.utils.learning_rate.MultiLearningRateScheduler',
            'settings':{
                'boundaries': [10000, 500000],
                'scheduler_settings': [
                    {
                    'full_class_string': 'tensorflow.keras.optimizers.schedules.PolynomialDecay',
                    'settings': {
                        'initial_learning_rate': 0.01,
                        'end_learning_rate': 0.001,
                        'decay_steps': 10000,
                        },
                    },
                    {
                    'full_class_string': 'tensorflow.keras.optimizers.schedules.PolynomialDecay',
                    'settings': {
                        'initial_learning_rate': 0.001,
                        'end_learning_rate': 0.001,
                        'decay_steps': 490000,
                        },
                    },
                    {
                    'full_class_string': 'tensorflow.keras.optimizers.schedules.PolynomialDecay',
                    'settings': {
                        'initial_learning_rate': 0.001,
                        'end_learning_rate': 0.000001,
                        'decay_steps': 500000,
                        'power': 2,
                        },
                    },
                ]
            },
        },
    },
    'l1_regularization': 0.,
    'l2_regularization': 0.,
    'clip_gradients_value': ,
    'remove_nan_gradients': False,

    'validation_frequency': 100,
    'evaluation_frequency': 100,
    'save_frequency': 500,

    # Number of training iterations to train the model for
    'num_training_iterations': 1000000,
    
    # Additional keywords to the loss module used for training
    'additional_loss_module_kwargs': {
        'normalize_by_total_charge': False,
    },
}

#----------------.-------
# Reconstruction settings
#------------------------
reconstruction_settings: {
    'reco_output_file': '../data/reconstruction/{unique_name}/reconstruction_{unique_name}.hdf5',

    # Define which modules to run
    'calculate_covariance_matrix': False,
    'calculate_goodness_of_fit': False,
    'estimate_angular_uncertainty': False,
    'run_mcmc': False,
    'make_1d_llh_scans': False,

    # define which tensor to use as parameter_tensor (default: x_parameters)
    'parameter_tensor_name': 'x_parameters',
    # define seed (to seed from MC truth choose: 'x_parameters')
    'seed': 'MonopodFit4_PartialExclusion',
    # these are only relevant for the SeedLoaderMiscModule. This specifies
    # from which column names in the data table the parameters will be loaded
    'seed_parameter_names': ['x', 'y', 'z', 'zenith', 'azimuth',
                             'energy', 'time',
                         ],
    'seed_missing_value': 1.,
    'seed_missing_value_dict': {
    },
    'seed_float_precision': 'float32',

    # choose the otpimizer iterface:
    #   'scipy' or 'tfp' (tensorflow_probability)
    'reco_optimizer_interface': 'scipy',

    'scipy_optimizer_settings': {
        # 'method': 'L-BFGS-B',
        'method': 'BFGS',
        'options': {
            # 'ftol': !!float 1e-7,
        }
    },

    'tf_optimizer_settings': {
        'method': 'bfgs_minimize',
        'x_tolerance': 0.001,
    },

    # Perform minimization in transformed and normalized parameter space
    # if True. This is usually desired as it may facilitate minimization.
    'minimize_in_trafo_space': True,

    # Specify which parameters to fit.
    # If True, the parameter is minimized doing reconstruction, otherwise it
    # is held constant.
    # Set default value which will apply to all parameters, except if stated
    # otherwise in the 'minimize_parameter_dict'
    'minimize_parameter_default_value': True,
    # Settings defined here overwrite the default value
    # Entries must have the form: {parameter_name: value}
    'minimize_parameter_dict': {

    },
}

#-----------------------
# Model Manager settings
#-----------------------

# Settings for model manager class
model_manager_settings: {

    # The loss module class to use
    'model_manager_class': 'egenerator.manager.source.SourceManager',

    # restore model if True, otherwise start from scratch
    'restore_model' : True,

    # These settings are used to configure the model manager and may not change
    config: {

        # Path to where the manager will be saved to and loaded from
        'manager_dir': '../data/training/{unique_name}/manager',

        # Define which model parameters to use for the I3Particle
        # [x, y, z, zenith, azimuth, energy, time]
        'I3ParticleMapping': {
            'x': 'cascade_x',
            'y': 'cascade_y',
            'z': 'cascade_z',
            'zenith': 'cascade_zenith',
            'azimuth': 'cascade_azimuth',
            'energy': 'cascade_energy',
            'time': 'cascade_time',
        },
    },
}

#-----------------------
# Data Iterator settings
#-----------------------

# These settings describe the data iterators
data_iterator_settings: {

    # The training data iterator
    'training': {
        'batch_size': 32,
        'num_splits': ,
        'file_capacity': 10,
        'batch_capacity': 500,
        'dataset_capacity': 500,
        'num_jobs': 10,
        'num_add_files': 5,
        'num_repetitions': 3,
        'pick_random_files_forever': False,
        'input_data': [
          '/data/user/fschluter/eg-data/electrons/unbinned/set_3/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_4/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_5/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_6/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_7/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_8/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_9/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_10/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_11/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_12/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_13/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_14/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_15/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
        ],
    },

    # The trafo data iterator
    'trafo': {
        'batch_size': 32,
        'num_splits': ,
        'file_capacity': 1,
        'batch_capacity': 2,
        'num_jobs': 12,
        'num_add_files': 1,
        'num_repetitions': 1,
        'pick_random_files_forever': False,
        'input_data': [
          '/data/user/fschluter/eg-data/electrons/unbinned/set_3/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_4/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_5/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_6/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_7/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_8/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_9/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_10/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_11/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_12/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_13/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_14/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_15/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
        ],
    },

    # The validation data iterator
    'validation': {
        'batch_size': 32,
        'num_splits': ,
        'file_capacity': 10,
        'batch_capacity': 10,
        'dataset_capacity': 10,
        'num_jobs': 10,
        'num_add_files': 5,
        'num_repetitions': 1,
        'pick_random_files_forever': False,
        'input_data': [
          '/data/user/fschluter/eg-data/electrons/unbinned/set_0/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_1/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_2/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
        ],
    },

    # The test data iterator
    'test': {
        'batch_size': 1,
        'num_splits': ,
        'file_capacity': 1,
        'batch_capacity': 10,
        'num_jobs': 1,
        'num_add_files': 0,
        'num_repetitions': 1,
        'sample_randomly': False,
        'pick_random_files_forever': False,
        'input_data': [
          '/data/user/fschluter/eg-data/electrons/unbinned/set_16/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_17/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
          '/data/user/fschluter/eg-data/electrons/unbinned/set_18/Gen1k_10TeV_EMinus_FTP_V3_*.hdf5',
        ],
    },
}

#---------------------
# Loss module settings
#---------------------

# Settings for the loss module class
loss_module_settings: {
    # The loss module class to use
    'loss_module': 'egenerator.loss.default.DefaultLossModule',

    config: {
        # the float precision to use
        'float_precision': 'float32',

        'add_normalization_term': True,

        # choose the loss function to use
        'loss_function_name': 'unbinned_extended_pulse_llh',  # this implies a Poisson likelihood for the charge
    },
}

#---------------------------
# Evaluation module settings
#---------------------------

# Settings for the evaluation module class
evaluation_module_settings: {

    # The loss module class to use
    'evaluation_module':,
    config: {
    },
}

#-----------------------------
# Data Transformation settings
#-----------------------------
data_trafo_settings: {
    'float_precision': 'float64',
    'norm_constant': !!float 1e-6,
    'num_batches': 2000,
    'model_dir': '../data/trafo/{unique_name}',
}

#----------------------
# Data Handler settings
#----------------------

# Settings for the data handler class
data_handler_settings: {

    # The data handler class to use
    'data_handler': 'modular.ModuleDataHandler',

    # -------------------
    # DataModule Settings
    # -------------------
    # which data module to use
    'data_module': 'pulse_data.PulseDataModule',

    # settings for the data module
    'data_settings':{
        'pulse_key': 'I3MCPESeriesMap',
        'pulse_is_mcpe': True,
        'dom_exclusions_key':,
        'time_exclusions_key':,
        'float_precision': 'float32',
        'add_charge_quantiles': False,
        'discard_pulses_from_excluded_doms': False,
    },

    # --------------------
    # LabelModule Settings
    # --------------------
    # which label module to use
    'label_module': 'cascades.CascadeGeneratorLabelModule',

    # settings for the label module
    'label_settings':{
        'shift_cascade_vertex': True,
        # logarithm on labels:
        # (x, y, z, zenith, azimuth, energy, time)?
        # 'parameter_names': ['x', 'y', 'z', 'zenith', 'azimuth', 'energy', 'time'],
        'trafo_log': [False, False, False, False, False, True, False],
        'label_key': 'LabelsDeepLearning',
        'float_precision': 'float32',
    },

    # ---------------------
    # WeightModule Settings
    # ---------------------
    # which weight module to use
    'weight_module': 'dummy.DummyWeightModule',

    # settings for the weight module
    'weight_settings':{},

    # -------------------
    # MiscModule Settings
    # -------------------
    # which misc module to use
    'misc_module': 'dummy.DummyMiscModule',

    # settings for the misc module
    'misc_settings':{},

    # -------------------
    # FilterModule Settings
    # -------------------
    # which filter module to use
    'filter_module': 'general_filter.GeneralFilterModule',

    # settings for the filter module
    'filter_settings':{
        'constraints': [
            # ['LabelsDeepLearning', 'cascade_z', '<', -250.],
        ],
    },
}

#---------------
# Model settings
#---------------

# Settings for the neural network model class
model_settings: {

    # The source class to use
    'model_class': 'egenerator.model.source.cascade.default.DefaultCascadeModel',

    config: {
        'keep_prob':,
        'add_opening_angle': True,
        'add_dom_coordinates': False,
        'num_local_vars': 0,
        'scale_charge': True,
        'scale_charge_by_relative_dom_efficiency': True,
        'scale_charge_by_global_dom_efficiency': False,
        'prevent_mixture_component_swapping': False,
        'estimate_charge_distribution': 'negative_binomial',
        'num_latent_models': 10,

        # This is a list of labels in addition to
        # (x, y, z, zenith, azimuth, energy, time) and snowstorm parameters
        'additional_label_names' : [
        ],

        # First convolutions
        'filter_size_list' : [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]],
        'num_filters_list' : [25, 500, 500, 500, 42],  # The last dimension should be 4 * num_asym_gauss + num_charge_pdf; num_asym_gauss = 10,  num_charge_pdf = 1 (poisson) or 2 (binominal)
        'method_list' : ['locally_connected',
                            'convolution', 'convolution', 'convolution',
                            'convolution',
                            ],
        'use_dropout_list' : False,
        'activation_list' : ['elu', 'elu', 'elu', 'elu', ''],
        'use_batch_norm_list' : False,
        'use_residual_list' : True,
    },
}

#----------------------
...
