---
##############
# Test config
#
# Detailed information on the parameters are given in the SetupManager
# class located in egenerator.settings.setup_manager.py.
##############

# Provide a unique name for the model
'unique_name': 'event_selection_starting_events_big'

#---------------------------
# General settings
#---------------------------
'float_precision': float32

#----------------------
# Data Handler settings
#----------------------

#----------------------
...
