check_values: {}
class_string: egenerator.data.modules.data.pulse_data.PulseDataModule
dependent_sub_components: []
event_generator_git_sha: be1d3a403807ddfe845650f5f9abe0280804473a
event_generator_origin: ssh://git@github.com/icecube/event-generator.git
event_generator_uncommitted_changes: true
event_generator_version: 1.0.1-dev
mutable_settings: {discard_pulses_from_excluded_doms: false, dom_exclusions_key: BrightDOMs,
  pulse_key: masked_pulses, time_exclusions_key: time_exclusion}
mutable_sub_components: []
settings: {add_charge_quantiles: false, config_data: null, float_precision: float32}
sub_component_configurations: {}
