__version__ = "0.0.0"
__author__ = "Mirco Huennefeld"
__author_email__ = "mirco.huennefeld@tu-dortmund.de"
__description__ = "IceCube Event Generator"
__url__ = "https://github.com/mhuen/event-generator"
